SELECT A.ID, A.NAME, COUNT(C.CAR_ID)
FROM BRANCHES A
    JOIN EMPLOYEES B
    ON A.ID = B.BRANCH_ID
    LEFT OUTER JOIN SELLINGS C 
    ON C.EMPLOYEE_ID = B.ID 
    AND C.CAR_ID = 306
GROUP BY A.ID
ORDER BY B.BRANCH_ID
