SELECT
A.ID "가게 ID", A.NAME, COUNT(*) "결제 횟수"
FROM
MERCHANTS A JOIN CARD_USAGES B ON A.ID = B.MERCHANT_ID
WHERE B.CATEGORY = 0 AND (NAME LIKE '%강남%' OR NAME LIKE '%논현%')
GROUP BY A.NAME
ORDER BY A.ID;